language: node_js
node_js:
  - "5"
install:
  - npm install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint-css
  - npm run lint-js
  - npm run test
  - npm run test-karma
addons:
  firefox: latest
